steps:
- id: 'Run apigeecli commands'
  name: ghcr.io/apigee/apigeecli:latest
  entrypoint: 'sh'
  args:
    - -c
    - |
      #setup preferences
      apigeecli prefs set --nocheck=true -o apigee-prd1
      apigeecli token cache --metadata-token

      # openapi deployment
      apigeecli apis create openapi  -f compras-api.yml  -n apidoiago4321