openapi: 3.0.0
info:
  title: Ultimas Compras API
  description: This API returns the result of last purchases.
  version: 1.0.0
servers:
- url: https://compras-api-yykwvlrz3q-uc.a.run.app
paths:
  /ultimas-compras:
    get:
      operationId: getUltimasCompras
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UltimasCompras'
          description: OK
      summary: Returns the result of last purchases.
      tags:
        - ultimas-compras
components:
  schemas:
    UltimasCompras:
      description: The result of last purchases.
      properties:
        ano:
          description: The year of the purchase.
          type: string
        cliente:
          description: The customer name.
          type: string
        cpf:
          description: The customer CPF.
          type: string
        id:
          description: The purchase ID.
          type: string
        mes:
          description: The month of the purchase.
          type: string
        valor:
          description: The purchase value.
          type: string
      title: UltimasCompras
      type: object
